"""s1_donor_lots_donor_requests_listing_donor_lot_id

Revision ID: 1292e1d6a854
Revises: 6a092294795f
Create Date: 2026-09-23 23:12:14.277570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1292e1d6a854'
down_revision: Union[str, Sequence[str], None] = '6a092294795f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_schema_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('condition', sa.Enum('working', 'for_parts', 'untested', 'no_guarantee', name='donor_part_condition'), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'negotiated', 'sold', 'hidden', name='donor_lot_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_schema_id'], ['device_schemas.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_company_id', sa.UUID(), nullable=False),
    sa.Column('seller_company_id', sa.UUID(), nullable=True),
    sa.Column('amount_rub', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['donor_lot_id'], ['donor_lots.id'], ),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('listings', sa.Column('donor_lot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'listings', 'donor_lots', ['donor_lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'donor_lot_id')
    op.drop_table('donor_requests')
    op.drop_table('donor_lots')
    # ### end Alembic commands ###
