"""be1_donor_photo_upload

Revision ID: 3be3cb5d4f37
Revises: 1292e1d6a854
Create Date: 2026-09-25 14:45:48.213028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be3cb5d4f37'
down_revision: Union[str, Sequence[str], None] = '1292e1d6a854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_owner_id'), 'photos', ['owner_id'], unique=False)
    op.create_index(op.f('ix_photos_owner_type'), 'photos', ['owner_type'], unique=False)
    op.create_table('donors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('device_schema_id', sa.UUID(), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('condition', sa.Enum('working', 'for_parts', 'untested', 'no_guarantee', name='donor_condition'), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='donor_status'), nullable=False),
    sa.Column('donor_lot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_schema_id'], ['device_schemas.id'], ),
    sa.ForeignKeyConstraint(['donor_lot_id'], ['donor_lots.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('inventree_part_id', sa.Integer(), nullable=True),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donor_parts')
    op.drop_table('donors')
    op.drop_index(op.f('ix_photos_owner_type'), table_name='photos')
    op.drop_index(op.f('ix_photos_owner_id'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
