"""baseline marketplace schema (T1)

Revision ID: 6a092294795f
Revises: 
Create Date: 2026-09-22 02:39:21.404605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a092294795f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # enum-типы могли остаться от предыдущей жизни БД — создаются идемпотентно
    for enum_name, values in (
        ("part_condition", ("working", "for_parts", "untested", "no_guarantee")),
        ("listing_status", ("active", "negotiated", "sold", "hidden")),
        ("deal_status", ("created", "paid_escrow", "shipped", "delivered", "completed", "refunded", "dispute")),
        ("escrow_status", ("created", "paid", "in_progress", "released", "refunded")),
    ):
        op.execute(
            "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '%s') THEN "
            "CREATE TYPE %s AS ENUM (%s); END IF; END $$;"
            % (enum_name, enum_name, ", ".join(f"'{v}'" for v in values))
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventree_company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('device_schemas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('inventree_donor_part_id', sa.Integer(), nullable=True),
    sa.Column('exploded_view_url', sa.Text(), nullable=False),
    sa.Column('hotspots', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventree_part_id', sa.Integer(), nullable=True),
    sa.Column('inventree_stock_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('device_schema_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('condition', sa.Enum('working', 'for_parts', 'untested', 'no_guarantee', name='part_condition', create_type=False), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'negotiated', 'sold', 'hidden', name='listing_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_schema_id'], ['device_schemas.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_company_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('created', 'paid_escrow', 'shipped', 'delivered', 'completed', 'refunded', 'dispute', name='deal_status', create_type=False), nullable=False),
    sa.Column('amount_rub', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=True),
    sa.Column('escrow_status', sa.Enum('created', 'paid', 'in_progress', 'released', 'refunded', name='escrow_status', create_type=False), nullable=False),
    sa.Column('sdek_order_uuid', sa.String(length=64), nullable=True),
    sa.Column('sdek_tracking', sa.String(length=64), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('deals')
    op.drop_table('listings')
    op.drop_table('device_schemas')
    op.drop_table('companies')
    # ### end Alembic commands ###
