"""be3_chat

Revision ID: be3_chat
Revises: caf5db912fa8
Create Date: 2026-09-26 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3_chat'
down_revision: Union[str, Sequence[str], None] = 'caf5db912fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: add chat tables (dialogs, dialog_participants, offers, messages).

    NB: offers must be created BEFORE messages, since messages.offer_id references
    offers.id (PostgreSQL FK requires the referenced table to exist first).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('listing_id', sa.UUID(), nullable=True),
        sa.Column('donor_lot_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
        sa.ForeignKeyConstraint(['donor_lot_id'], ['donor_lots.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogs_created_at'), 'dialogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dialogs_updated_at'), 'dialogs', ['updated_at'], unique=False)

    op.create_table('dialog_participants',
        sa.Column('dialog_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('dialog_id', 'user_id')
    )
    op.create_index(op.f('ix_dialog_participants_user_id'), 'dialog_participants', ['user_id'], unique=False)

    op.create_table('offers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('dialog_id', sa.UUID(), nullable=False),
        sa.Column('sender_id', sa.UUID(), nullable=False),
        sa.Column('price_rub', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='pending'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_dialog_id'), 'offers', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_offers_sender_id'), 'offers', ['sender_id'], unique=False)

    op.create_table('messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('dialog_id', sa.UUID(), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('kind', sa.String(length=16), nullable=False, server_default='text'),
        sa.Column('body', sa.Text(), nullable=False, server_default=''),
        sa.Column('offer_id', sa.UUID(), nullable=True),
        sa.Column('attachment_url', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_dialog_id_created'), 'messages', ['dialog_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_author_id'), 'messages', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: remove chat tables (reverse create order)."""
    op.drop_index(op.f('ix_messages_author_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_dialog_id_created'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_offers_sender_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_dialog_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_dialog_participants_user_id'), table_name='dialog_participants')
    op.drop_table('dialog_participants')
    op.drop_index(op.f('ix_dialogs_updated_at'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_created_at'), table_name='dialogs')
    op.drop_table('dialogs')
