"""be2_buy_requests

Revision ID: caf5db912fa8
Revises: 3be3cb5d4f37
Create Date: 2026-09-25 22:42:04.739243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf5db912fa8'
down_revision: Union[str, Sequence[str], None] = '3be3cb5d4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('part', 'phone', name='buy_request_type'), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('cond', sa.String(length=32), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'closed', name='buy_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buy_requests_brand', 'buy_requests', ['brand'], unique=False)
    op.create_index('ix_buy_requests_buyer_id', 'buy_requests', ['buyer_id'], unique=False)
    op.create_index('ix_buy_requests_status', 'buy_requests', ['status'], unique=False)
    op.create_index('ix_buy_requests_type', 'buy_requests', ['type'], unique=False)
    op.create_table('buy_request_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buy_request_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('offer_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='buy_response_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buy_request_id'], ['buy_requests.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buy_request_responses_buy_request_id', 'buy_request_responses', ['buy_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buy_request_responses_buy_request_id', table_name='buy_request_responses')
    op.drop_table('buy_request_responses')
    op.drop_index('ix_buy_requests_type', table_name='buy_requests')
    op.drop_index('ix_buy_requests_status', table_name='buy_requests')
    op.drop_index('ix_buy_requests_buyer_id', table_name='buy_requests')
    op.drop_index('ix_buy_requests_brand', table_name='buy_requests')
    op.drop_table('buy_requests')
    # ### end Alembic commands ###
